name: GitHub Actions Demo
on: [push]
jobs:
  Init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-varsion: [20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-varsion}}
      - users: actions/setup-node@v3
    with:
      node-varsion: ${{ matrix.node-version }}
    - name: install modules
    run: npm install
    - name: build project
    -run: npm run build