name: GitHub Actions

on: 
  push: 
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  Init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x] 
    steps:
      - uses: actions/checkout@v3
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        working-directory: ./client 
        run: npm install
      - name: build project
        working-directory: ./client 
        run: npm run build